# Файл конфигурации для хостинга Render.com
# Он настраивает сервис для развертывания вашего React-приложения как статического сайта
# и добавляет правило для корректной работы React Router.

services:
  # Определяем сервис для фронтенда
  - type: static_site # Указываем тип сервиса: статический сайт
    name: taxa-ai-frontend # Название вашего сервиса (может быть любым)
    env: static # Среда выполнения
    
    # Команда для сборки вашего проекта. Render выполнит её при каждом развертывании.
    buildCommand: npm install && npm run build
    
    # Папка, в которой находится собранный проект. Vite по умолчанию использует 'dist'.
    staticPublishPath: ./dist
    
    # Правила маршрутизации. Это самая важная часть для SPA.
    routes:
      - type: rewrite # Тип правила: перезапись URL
        # Перехватывать все запросы к любым страницам...
        source: /*
        # ...и вместо поиска файла по этому пути, всегда отдавать главный файл index.html.
        # React Router на клиенте затем сам определит, какой компонент показать.
        destination: /index.html